import { useState } from "react";
import { Container, Stack, Divider } from "@mui/material";

import VideoUploader from "../components/Upload/VideoUploader";
import AutoCaptionSection from "../components/Captions/AutoCaptionSection";
import CaptionStyleSelector from "../components/Preview/CaptionStyleSelector";
import RemotionPreview from "../components/Preview/RemotionPreview";

export default function Home() {
  const [videoId, setVideoId] = useState(null);
  const [captions, setCaptions] = useState([]);
  const [captionStyle, setCaptionStyle] = useState("bottom");

  /**
   * Called AFTER successful upload
   * videoId is generated by backend
   */
  const handleUploadSuccess = (uploadedVideoId) => {
    setVideoId(uploadedVideoId);
    setCaptions([]); 
  };

  /**
   * Called AFTER captions are generated
   * captions are normalized (Phase 4 output)
   */
  const handleCaptionsGenerated = (generatedCaptions) => {
    setCaptions(generatedCaptions);
  };

  /**
   * Video source for Remotion preview
   * (temporary approach – backend static serving or blob URL)
   */

  let videoRef = localStorage.getItem("videoId")
  const videoSrc = videoId
    ? `http://localhost:5000/temp/videos/${videoRef}.mp4`
    : null;

    console.log("videoSrcvideoSrc",videoSrc)

  return (
    <Container maxWidth="lg">
      <Stack spacing={5} py={4}>
 
        <VideoUploader onUploadSuccess={handleUploadSuccess} />

        <AutoCaptionSection
          videoId={videoId}
          onCaptionsGenerated={handleCaptionsGenerated}
        />

        {captions.length > 0 && (
          <>
            <Divider />

         
            <CaptionStyleSelector
              value={captionStyle}
              onChange={setCaptionStyle}
            />

       
            <RemotionPreview
              videoSrc={videoSrc}
              captions={captions}
              captionStyle={captionStyle}
            />
          </>
        )}
      </Stack>
    </Container>
  );
}
